### ISSUE TITLE
Error in console with multiple gravity forms on single page with this plugin

### ISSUE THREAD

**Issue by BhargavBhandari90** [bhays/gravity-forms-javascript-validation#6]
I added three forms on a single page and enable javascript validation in one of the forms.

And when I submit any form then it throws error in console like
`(index):283 Uncaught ReferenceError: gf_submitting_10 is not defined(…)`

Here is the screenshot for that : [image](https://drive.google.com/open?id=0B8EpOcjaFfkHMVRLMk5HOEhxMnc)

**Comment by BhargavBhandari90** [comment]
Improved title

**Comment by BhargavBhandari90** [comment]
Improved title

**Comment by bhays** [comment]
I believe I ran into that issue as well when originally building this. Unfortunately, this was never production ready and that's why it's only here and not in the WordPress repository. 

It looks like there may be a good alternative at https://wordpress.org/plugins/real-time-validation-for-gravity-forms/ or, I'm happy to accept a pull request if you'd like to make changes.
